language:
    python
python:
    - "2.7"
    - "3.5"

install:
    - pip install python-coveralls
    - pip install nose

script:
    cd src
    nosetests --with-coverage --cover-package=intuition

after_success:
    - coveralls