language:
    python
python:
    - "3.5"
    - "3.6"
install:
    - pip install nose coveralls

before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    
script:
    - nosetests --with-coverage --cover-package=intuition -v

after_success:
    - coveralls