language:
    python
python:
    - "2.7"
    - "3.4.2"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"

install:
    - pip install nose coveralls

before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    
script:
    - nosetests --with-coverage --cover-package=intuition -v

after_success:
    - coveralls